# -*- coding: utf-8 -*-
"""12_Hugging-face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-T0KIFjcDq28ZEECj2KZQQL_6X1rn8Z

# **Hugging Face Transformers Asoslari**

### Ushubu darsda biz Hugging Face kutubxonasidan foydalanib, oldindan shug'ullantirilgan (pre-trained) Transformer modellarini bir necha qator kod bilan ishlashini o'rganamiz

## **Asosiy vazifalar:**

### pipeline funksiyasi yordamida bir necha NLP (tabiiy tilga ishlov berish) vazifalarini ko'rib chiqamiz:

### 1.Sentiment Analysis (Matn hissiyotini tahlil qilish)

### 2.Fill-Mask (Niqoblangan so'zni to'ldirish)

### 3.Named Entity Recognition (NER- Nomli obyektlarni aniqlash)
"""

!pip install transformers

"""### `CPU` (Central Processing Unit):

Vazifasi: CPU kompyuterning "miya"si hisoblanadi. U umumiy maqsadli hisoblash ishlari, ya'ni ketma-ketlikda bajariladigan turli xil vazifalarni (operatsion tizimni boshqarish, dasturlarni ishga tushirish, veb-sahifalarni yuklash, Word hujjatlari bilan ishlash) bajarish uchun mo'ljallangan.

### `T4 GPU` (NVIDIA Tesla T4 Graphics Processing Unit):

Vazifasi: T4 GPU, oddiy grafik kartalardan farqli o'laroq, ayniqsa sun'iy intellekt (AI), mashinani o'rganish (ML), chuqur o'rganish (Deep Learning) va yuqori unumdorlikdagi hisoblashlar (High-Performance Computing - HPC) kabi vazifalar uchun mo'ljallangan.

Shuning uchun Runtime bo'limidagi `CPU` turi (type) dan `T4 GPU` ga o'tkazib oldik tezroq ishlashi va ish unumdorligi uchun

## **1.Sentiment Analysis (Matn hissiyotini tahlil qilish)**
"""

from transformers import pipeline

classifier = pipeline("sentiment-analysis")

result = classifier("I've been waiting for a HuggingFace course my whole life.")

result

"""
from transformers import pipeline: Bu qator Hugging Face Transformers kutubxonasidan pipeline funksiyasini yuklaydi. pipeline - bu oldindan o'qitilgan (pre-trained) Transformer modellaridan foydalanishni juda soddalashtiradigan yuqori darajadagi funksiya.

classifier = pipeline('sentiment-analysis'): Bu buyruq ishga tushirilganda, transformers kutubxonasi "pardalar ortida" bir nechta ishni amalga oshiradi:

Modelni tanlash: sentiment-analysis vazifasiga mos keladigan oldindan o'qitilgan modelni avtomatik ravishda tanlaydi (masalan, distilbert-base-uncased-finetuned-sst-2-english kabi). Bu model juda katta matn va teglar (label) ma'lumotlar to'plamida o'qitilgan bo'lib, ijobiy va salbiy hissiyotlarni aniqlashni o'rgangan.

Tokenizatorni yuklash: Tanlangan modelga mos keladigan tokenizatorni yuklaydi. Tokenizator xom matnni model tushunadigan formatga (raqamli IDlar, ko'pincha so'zlarni kichikroq birliklarga ajratgan holda) aylantirish uchun javobgardir.

Modelni yuklash: Oldindan o'qitilgan neyron tarmoq modelini (bu holda DistilBERT kabi Transformer modelini) xotiraga yuklaydi. Bu model o'qitish davomida millionlab parametrlarni o'rgangan bo'ladi.

Vazifaga xos 'bosh' (head): Sentiment tahlili uchun model bazaviy Transformer ustida klassifikatsiya 'boshi'ga ega bo'ladi. Bu 'bosh' Transformer'dan olingan abstrakt raqamli tasvirlarni oladi va turli hissiyot sinflari (masalan, IJOBIY, SALBIY) uchun ballar beradi.
result = classifier("I've been waiting for a HuggingFace course my whole life."): Siz matnni classifier ob'ektiga uzatganingizda:

Tokenizatsiya: Kiritilgan matn avval yuklangan tokenizator tomonidan tokenizatsiya qilinadi. U jumlani raqamli IDlar ketma-ketligiga aylantiradi va model talab qiladigan maxsus tokenlarni (masalan, [CLS] va [SEP]) qo'shadi.

Modelga kiritish: Tokenizatsiya qilingan kiritma (raqamli IDlar) keyin oldindan o'qitilgan sentiment tahlili modeliga beriladi.

Oldinga yo'nalishli o'tish (Forward Pass): Model kiritmani o'zining ko'p qatlamlari orqali qayta ishlaydi. Har bir qatlam kiritmani o'zgartiradi va oxir-oqibat matnning ma'nosini yuqori o'lchovli tasvirini hosil qiladi.

Bashorat: Modelning klassifikatsiya boshi bu tasvirni oladi va mumkin bo'lgan sentiment teglarining ehtimollik taqsimotini chiqaradi (masalan, IJOBIY uchun 95%, SALBIY uchun 5%).

Natijani shakllantirish: pipeline keyin bu bashoratni foydalanuvchiga qulay lug'at (dictionary) formatida shakllantiradi, unda bashorat qilingan label (masalan, 'POSITIVE') va uning score (masalan, 0.9598) ko'rsatiladi.

Umuman olganda, pipeline model va tokenizatorni yuklash, bashoratlarni amalga oshirish kabi barcha murakkab qadamlarni yashiradi. Bu esa foydalanuvchilarga oldindan o'qitilgan Transformer modellarining kuchidan foydalanib, bir necha qator kod bilan NLP vazifalarini bajarish imkonini beradi."""

classifier = pipeline("sentiment-analysis")

result_2 = classifier("Menda juda ko'p darsliklar bor va hammasi juda foydali.")

result_2

# Bunda model faqat ingliz tilida o'qitilganligi sababli o'zbek tilidagi possitive
# gapni ham negative deb chiqarmoqda

classifier = pipeline("sentiment-analysis")

result_3 = classifier("I have many lessons about program and they all my lessons very usefull.")

result_3

"""## **2.Fill-Mask (Niqoblangan so'zni to'ldirish)**"""

fill_mask = pipeline("fill-mask")

fill_mask("Deep Learning is <mask>")

# Bunda <mask> bu belgi gapni davom ettiradi yani yozilish ehtimoli
# yuqori bo'lgan so'zlarni chiqaradi va pastda bir nechta awesome, Coming kabi bir nechta variantlarni chiqargan.

fill_mask = pipeline("fill-mask")

fill_mask("The capital of the USA is <mask>")

fill_mask = pipeline("fill-mask")

fill_mask("I have much money there for I spend all my money for <mask>")

"""## **3.Named Entity Recognition (NER- Nomli obyektlarni aniqlash)**"""

# ner = pipeline('ner', grouped_entities=True)
ner = pipeline('ner')


ner("My name is Olimjon, I'm building a course.")

ner = pipeline('ner')

ner("My name is Sylvain and I work at Hugging-Face in New-York.")

from transformers import pipeline

# Modeldan aniq foydalanib, grouped_entities=True bilan qayta urinib ko'ramiz
# Yuqoridagi xatoni hisobga olib, 'grouped_entities=True' argumentini olib tashlaymiz.
# Agar guruhlangan natijalar kerak bo'lsa, ularni qo'lda guruhlash mumkin.
ner_grouped = pipeline('ner', model='dbmdz/bert-large-cased-finetuned-conll03-english')

# Natijani tekshirish
ner_grouped("My name is Sylvain and I work at Hugging-Face in New-York.")

# Natijada siz matndagi uchta asosiy nomli ob'ektni olishga muvaffaq bo'ldingiz:
# {'entity_group': 'PER', 'score': 0.9982584, 'word': 'Sylvain', 'start': 11, 'end': 18} - Bu 'Sylvain'
# so'zi bitta shaxs (PER) ob'ekti sifatida guruhlanganini ko'rsatadi, ishonch bali yuqori.
# {'entity_group': 'ORG', 'score': 0.9735328, 'word': 'Hugging-Face', 'start': 33, 'end': 45} - 'Hugging-Face'
# bitta tashkilot (ORG) ob'ekti sifatida guruhlangan.
# {'entity_group': 'LOC', 'score': 0.97783244, 'word': 'New-York', 'start': 49, 'end': 57} - 'New-York' bitta joy (LOC) ob'ekti sifatida guruhlangan.

ner = pipeline('ner')

ner("I have a car in my home.")

ner = pipeline('ner')

# Shaxs, tashkilot va joy nomlarini o'z ichiga olgan misol
ner("sardor va Rahim hozirda Londonda ishlaydi va o'qiydi.")

"""# **NEW SECTION**

## Bunday yuqorida biz ishlaganimiz kabi modellar ko'p hisoblanadi

## Pastda yana boshqa modellar bilan ham tanishib ko'ramiz

## **4. Question Answering (Savol-Javob)**

Matn asosida savollarga javob berish uchun `question-answering` pipeline'ini ishga tushiramiz va misol sifatida savol-javob qilib ko'ramiz.
"""

from transformers import pipeline

qa_pipeline = pipeline("question-answering")
# Modelni chaqirib olamiz

context = "Hugging Face Transformers is a Python library providing pre-trained models for Natural Language Processing (NLP) tasks such as text classification, information extraction, translation, and text generation. It supports frameworks like PyTorch, TensorFlow, and JAX."
# context o'zgaruvchisiga matn kiritamiz
question = "What is Hugging Face Transformers?"
# va shu yuqoridagi matn asosida savol beramz

result = qa_pipeline(question=question, context=context)
# Bunda savolga javob beriladi

print(result)
# natijani print qilamiz

# Hamda Python library deb javob berilmoqda

from transformers import pipeline

qa_pipeline = pipeline("question-answering", model="distilbert/distilbert-base-cased-distilled-squad")

context = "Hugging Face Transformers is a Python library providing pre-trained models for Natural Language Processing (NLP) tasks such as text classification, information extraction, translation, and text generation. It supports frameworks like PyTorch, TensorFlow, and JAX."
question = "What is Hugging Face Transformers?"

result = qa_pipeline(question=question, context=context)

print(result)

"""## Ushbu kod matnni xulosa qilish (summarization) vazifasini bajaradi. Ya'ni, uzun matndan (long_text o'zgaruvchisidagi matndan) uning asosiy g'oyasini qisqacha shaklda chiqarib beradi. Misolimizdagi sshleifer/distilbart-cnn-12-6 nomli model yordamida matn qisqartiriladi."""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 1. Provide a long piece of text
long_text = "Hugging Face Transformers is an open-source library that provides thousands of pre-trained models to perform tasks on texts such as classification, information extraction, question answering, summarization, translation, text generation, and more. It supports interoperability between PyTorch, TensorFlow, and JAX frameworks. These models are highly optimized and can be used directly for inference, fine-tuned on custom datasets, or integrated into larger applications. The library is widely adopted in both research and industry due to its ease of use, robust features, and extensive community support. It democratizes access to state-of-the-art NLP models, enabling developers and researchers to build powerful language-aware applications with minimal effort."

# 2. Load the tokenizer and model for summarization
model_name = "sshleifer/distilbart-cnn-12-6"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# 3. Tokenize the input text
inputs = tokenizer(long_text, max_length=1024, truncation=True, return_tensors="pt")

summary_ids = model.generate(
    inputs["input_ids"],
    max_length=100,
    min_length=30,
    do_sample=False
)

# 5. Decode the summary IDs back to text
summarized_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# 6. Print the summarized text
print(summarized_text)

"""## Ushbu kod Ingliz tilidan Fransuz tiliga tarjima qilish vazifasini bajaradi. U Helsinki-NLP/opus-mt-en-fr nomli model va uning tokenizatorini yuklab oladi. So'ngra, berilgan inglizcha matnni (english_text) tokenizatsiya qiladi, model yordamida uni fransuz tiliga tarjima qiladi va yakuniy tarjima qilingan matnni chop etadi."""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 2. Initialize a translation pipeline for English to French by directly loading model and tokenizer
model_name = "Helsinki-NLP/opus-mt-en-fr"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# 3. Define a sample English text to be translated
english_text = "Hello, how are you today? I hope you are having a good time."

# Tokenize the input text
inputs = tokenizer(english_text, return_tensors="pt")

# 4. Generate the translation
translated_ids = model.generate(**inputs)

# 5. Decode and print the translated text
translated_text = tokenizer.decode(translated_ids[0], skip_special_tokens=True)
print(translated_text)

"""## Ushbu kod matn generatsiyasi (text generation) vazifasini bajaradi. Ya'ni, berilgan boshlang'ich matn (prompt) asosida ("Life is beautiful and I always") gpt2 modeli yordamida matnni davom ettirib, yangi matn yaratadi."""

from transformers import pipeline

# 2. Initialize a text-generation pipeline, explicitly specifying 'gpt2'
gen = pipeline("text-generation", model="gpt2")

# 3. Define a starting text prompt in English
prompt = "Life is beautiful and I always"

# 4. Call the text-generation pipeline with the prompt
generated_text = gen(prompt, max_length=50, num_return_sequences=1)

# 5. Print the generated text
print(generated_text[0]['generated_text'])

"""## `from transformers import pipeline`

## Biz faqat bu yuqoridagi kutubxona ichidagi modellarni sinab ko'rdik ammo bunga o'xshagan boshqa kutubxonalar ham mavjud hisoblanadi

## Misil uchun:

## `SpaCy`

## `NLTK (Natural Language Toolkit)`

## `Gensim`

## `PyTorch va TensorFlow`

## `StanfordNLP / Stanza` va boshqalar.

"""

